// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iobsuogvapsgkutugyfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvYnN1b2d2YXBzZ2t1dHVneWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTM0NDAsImV4cCI6MjA2ODMyOTQ0MH0.XZu7J-OM2op0JzwO2ho-zhdodg10RAzR5KHHMte_EgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});